version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5438:5432
    environment:
      POSTGRES_DB: lifecycle
      POSTGRES_USER: lifecycle
      POSTGRES_PASSWORD: lifecycle
